### ISSUE TITLE
Updating the readme file for this project

### ISSUE THREAD

**Issue by mrbhatt2348** [mrbhatt2348/iBlog#1]

**Comment by Code1705** [comment]
I am willing to make a fresh up-to date Readme file for this project , please assign me this issue under JWOC

**Comment by vermaanurag1532** [comment]
I want to contribute on this project and maintain this project

**Comment by purbakundu** [comment]
i want to contribute

**Comment by mnik7044** [comment]
Hii @mrbhatt2348 is this issue assigned yet, if not I want to work on it.
