### ISSUE TITLE
[Bug] Links invisible in Dark mode

### ISSUE THREAD

**Issue by pooranjoyb** [mrbhatt2348/iBlog#101]
## Related Screenshot
![bug](https://user-images.githubusercontent.com/90945182/221882497-d0d906ec-d0a6-416d-ac0a-6fc6a9ba6d24.png)

**Comment by ayushi1709-20** [comment]
Please assign me this issue under JWOC.

**Comment by mrbhatt2348** [comment]
> ## I would like to work on this issue under JWOC 2023. Please assign me this issue @mrbhatt2348 
> 
> ## Related Screenshot
> ![bug](https://user-images.githubusercontent.com/90945182/221882497-d0d906ec-d0a6-416d-ac0a-6fc6a9ba6d24.png)
> 

Go on

**Comment by pooranjoyb** [comment]
Closing this as someone might have fixed it in other PR 😃
