### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by S-ishita** [mrbhatt2348/iBlog#102]
Favicon is missing in the code.Please assign this issue to me under JWOC

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC

**Comment by mrbhatt2348** [comment]
> Favicon is missing in the code.Please assign this issue to me under JWOC

Go on @S-ishita

**Comment by S-ishita** [comment]
> > Favicon is missing in the code.Please assign this issue to me under JWOC
> 
> Go on @S-ishita

Hey @mrbhatt2348 despite this message it is not showig assigned..please check and  i have also linked the pr kindly review
