### ISSUE TITLE
Animations addition

### ISSUE THREAD

**Issue by ritika728** [mrbhatt2348/iBlog#105]
Hey, I would like to open this issue under JWOC. Animations makes a website attractive. I wish to add different animations (fade in, right, left , up etc.) to the entire website.

**Comment by ritika728** [comment]
@mrbhatt2348 can you please assign me this issue

**Comment by mrbhatt2348** [comment]
> @mrbhatt2348 can you please assign me this issue 

@ritika728 go on, and congratulations for 100+ points

**Comment by ritika728** [comment]
Thank you! 😄
