### ISSUE TITLE
want to add a well designed log in page 

### ISSUE THREAD

**Issue by Ritu-2001** [mrbhatt2348/iBlog#11]

**Comment by Ritu-2001** [comment]
can you please assign me??

**Comment by mrbhatt2348** [comment]
> can you please assign me??

I can assign only one task at a time, to get yourself assigned to this task, first complete the task in which you are currently assigned.

**Comment by mrbhatt2348** [comment]
> has anyone done the login page ,I would love to contribute

No, you can add the issue, I will assign it to you after the coding period starts i.e. after 15th

**Comment by ADITI-2003** [comment]
Hello mentor, 
I want to add a login page, please assign me this issue.
Thank you.

**Comment by PrachiSingh66** [comment]
Hello, I want to work on this issue under JWOC so please assign it to me.
Thank you

**Comment by vermaanurag1532** [comment]
I want to contribute on this issue under JWOC

**Comment by SubhajitB05** [comment]
I want to contribute on this issue under JWOC

**Comment by ADITI-2003** [comment]
Hello mentor,
As I am working on this issue, I want to ask that the login page design is to be shown in comments ? And the work is to be done on canva or code file for login page?
Thank you

**Comment by Aniket-011** [comment]
Please assign me this issue under JWOC

**Comment by Code1705** [comment]
i want to contribute in this issue , please assign me this under JWOC .
