### ISSUE TITLE
Add header in the testimonials section

### ISSUE THREAD

**Issue by zugzwang03** [mrbhatt2348/iBlog#110]
I want to add the header of navbar and other entities in the testimonials page under JWOC'23.
![image](https://user-images.githubusercontent.com/95460021/223398185-9317ee97-8bb2-4bdd-ad47-a86103d789cb.png)

**Comment by zugzwang03** [comment]
Basically, it will look like this then 
![image](https://user-images.githubusercontent.com/95460021/223398606-fefba550-c903-4bca-acdd-56884e6f732a.png)

**Comment by zugzwang03** [comment]
@mrbhatt2348 kindly look into this

**Comment by mrbhatt2348** [comment]
> @mrbhatt2348 kindly look into this

@zugzwang03 go on
