### ISSUE TITLE
Add home button in login signup page

### ISSUE THREAD

**Issue by S-ishita** [mrbhatt2348/iBlog#111]
There is no way to navigate to home page after visiting login signup page.Hence I want to add home icon to it. Please assign this issue to me under JWOC.

**Comment by S-ishita** [comment]
Page will look like this after changes and home button will redirect to homepage

![Screenshot from 2023-03-08 14-22-41](https://user-images.githubusercontent.com/104543751/223667667-b1b35cc8-4031-49ad-ad70-fef7587e19b9.png)

**Comment by mrbhatt2348** [comment]
> Page will look like this after changes and home button will redirect to homepage
> 
> ![Screenshot from 2023-03-08 14-22-41](https://user-images.githubusercontent.com/104543751/223667667-b1b35cc8-4031-49ad-ad70-fef7587e19b9.png)
> 

@S-ishita go on
