### ISSUE TITLE
Improve contact us page

### ISSUE THREAD

**Issue by Neha00011** [mrbhatt2348/iBlog#112]
I want to work on this issue under jwoc.Kindly assign this issue to me under JWOC (phase 2)

**Comment by mrbhatt2348** [comment]
> I want to work on this issue under jwoc.Kindly assign this issue to me under JWOC (phase 2)

@Neha00011 go on

**Comment by khushimarothi** [comment]
This issue is already created please don't go against the rules.
@mrbhatt2348 you should better respond on #90

**Comment by Neha00011** [comment]
@mrbhatt2348 please add jwoc and difficulty tag same as  pr.

**Comment by mrbhatt2348** [comment]
> @mrbhatt2348 please add jwoc and difficulty tag same as  pr.

It is already added...
