### ISSUE TITLE
want to add CSS card animation effect

### ISSUE THREAD

**Issue by Ritu-2001** [mrbhatt2348/iBlog#12]

**Comment by mrbhatt2348** [comment]
@Ritu-2001 I have assigned you for this issue, this is an medium issue, to get your points, you will need to complete this issue within 2 days i.e. before 05:28pm 13-02-2023

**Comment by mrbhatt2348** [comment]
@Ritu-2001 I'm sorry, as the contribution period is not yet started, you are not required to do anything of now, add the pr after contribution period will start

**Comment by Swadhin2001** [comment]
I want to work on this issue. Please assign it to me.

**Comment by mrbhatt2348** [comment]
> I want to work on this issue. Please assign it to me.

Done

**Comment by Aarav238** [comment]
I would like to work on it @mrbhatt2348

**Comment by yeager404** [comment]
Would like to work on this issue. I can make a smooth animation for the cards. Can you elaborate on want kind of modifications you are looking for ?

**Comment by yeager404** [comment]
I would like to work on this issue. Kindly consider assigning this to me. Under JWOC

**Comment by Sarita-021** [comment]
hi @mrbhatt2348  I would like to work on the issue . 
Can you assign it to me. underJWOC

**Comment by PrachiSingh66** [comment]
I want to work on this issue under JWOC so please assign it to me

**Comment by KrunalGupta02** [comment]
I want to work on this issue under JWOC

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue, please assign it to me under JWOC.

**Comment by vermaanurag1532** [comment]
I want to work on this issue under JWOC

**Comment by Swadhin2001** [comment]
I want to work on this issue under JWOC

**Comment by Aniket-011** [comment]
Please assign me this issue under JWOC
