### ISSUE TITLE
Navbar not working properly.

### ISSUE THREAD

**Issue by RishabhJain0721** [mrbhatt2348/iBlog#122]
### Found two bugs : ###
* The navbar styling is not working properly in *_Home_* and *_FAQ_* sections.
* The *_FAQ_* section is not accessible from *_Testimonials_* section.

[iBlog - Heaven for bloggers (1).webm](https://user-images.githubusercontent.com/107767172/224476748-cf835873-d720-454d-8787-25b27b097780.webm)

Please assign this issue to me under JWOC.

**Comment by Viveksati5143** [comment]
@mrbhatt2348 Close this issue as my pr solving the same has already been merged.
