### ISSUE TITLE
Add testimonial Section

### ISSUE THREAD

**Issue by Riya14-dangra** [mrbhatt2348/iBlog#16]
As there is a home, about ,contact section in this website I want to add testimonial section 
The goal of a testimonial is to show the potential blog reader that other customers were happy using your this website. The more your satisfied customers are reliable, the more the testimonial is trustworthy.

@mrbhatt2348  can you please assign this issue to me under JWOC 2K23.I want to work on it.
Hope you allow me to work on this issue!!

It will look something like this with well UI designed
![blog](https://user-images.githubusercontent.com/84792579/218520752-9b48b32b-787b-47a6-87e5-ec2f05da6562.jpg)

**Comment by mrbhatt2348** [comment]
> As there is a home, about ,contact section in this website I want to add testimonial section The goal of a testimonial is to show the potential blog reader that other customers were happy using your this website. The more your satisfied customers are reliable, the more the testimonial is trustworthy.
> 
> @mrbhatt2348 can you please assign this issue to me under JWOC 2K23.I want to work on it. Hope you allow me to work on this issue!!
> 
> It will look something like this with well UI designed ![blog](https://user-images.githubusercontent.com/84792579/218520752-9b48b32b-787b-47a6-87e5-ec2f05da6562.jpg)

Cool, i can assign it to you tomorrow... as the coding period starts

**Comment by manya0210** [comment]
Hello sir ..I want to contribute to this issue under jwoc

**Comment by KrunalGupta02** [comment]
I want to work on this issue under JWOC

**Comment by Atul-8115** [comment]
I want to work on this issue please assign it to me

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue, please assign it to me.

**Comment by SHYALI** [comment]
I want to work on this issue under jwoc
