### ISSUE TITLE
LOGIN PAGE DESIGN

### ISSUE THREAD

**Issue by ZablonOigo** [mrbhatt2348/iBlog#18]
I would like to design the login page for iBlog website

**Comment by 21b01a1276** [comment]
I want to work on this issue under JWOC

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC

**Comment by 21b01a1276** [comment]
hey, sorry  @mrbhatt2348  I dont know how to create login page

**Comment by ManasaKaza** [comment]
Thank you @mrbhatt2348 , May I know the alloted duration for this issue under jwoc

**Comment by mrbhatt2348** [comment]
> jwoc

You will get two days, but after a full review of your work, the pull request will be merged, so you can show your work regularly, and if you have any doubt, you can contact me on LinkedIn or discord server

**Comment by mrbhatt2348** [comment]
> Thank you @mrbhatt2348 , May I know the alloted duration for this issue under jwoc

You will get two days, but after a full review of your work, the pull request will be merged, so you can show your work regularly, and if you have any doubt, you can contact me on LinkedIn or discord server

**Comment by SubhajitB05** [comment]
I want to work on this issue under JWOC

**Comment by mrbhatt2348** [comment]
@ManasaKaza you will get 4 days to complete it

**Comment by Aniket-011** [comment]
Please assign me this issue under JWOC

**Comment by Neha00011** [comment]
I want to work on this issue under JWOC
