### ISSUE TITLE
Updating the contributing.md for the project

### ISSUE THREAD

**Issue by mrbhatt2348** [mrbhatt2348/iBlog#2]

**Comment by the-amazing-atharva** [comment]
I would like to work on it!

**Comment by mrbhatt2348** [comment]
> I would like to work on it!

Okay, just add a pr when your are done, I'll check it and then merge, if everything will be alright

**Comment by the-amazing-atharva** [comment]
ok!

**Comment by mrbhatt2348** [comment]
@the-amazing-atharva congratulations...
you have completed the issue on time, it was an easy issue, you will get the points accordingly.

**Comment by mrbhatt2348** [comment]
@the-amazing-atharva  I'm sorry, as the contribution period is not yet started, you are not required to do anything of now, add the pr after contribution period will start

**Comment by Monishparameswaran** [comment]
i would like to work on this issue under JWOC, please assign this to me

**Comment by purbakundu** [comment]
i want to contribute
