### ISSUE TITLE
Styling the navbar

### ISSUE THREAD

**Issue by vamsikrishnarh7** [mrbhatt2348/iBlog#26]
The old navbar is :

![old navbar](https://user-images.githubusercontent.com/89008784/218974402-0c6a7570-51b4-4085-a422-5463f4945b10.png)

**The updated navbar (expected) :**

![updated-navbar](https://user-images.githubusercontent.com/89008784/218974532-378fd424-ce73-4401-ab2c-861699ce53ba.png)

**Comment by vamsikrishnarh7** [comment]
I want to work on this issue under JWOC.
Please assign this to me.

**Comment by AimanSh123** [comment]
I want to work on this issue under JWOC so please assign it to me
