### ISSUE TITLE
Adding Favicon to the website.

### ISSUE THREAD

**Issue by mnik7044** [mrbhatt2348/iBlog#28]
Hii @mrbhatt2348 please assign me this issue.

**Comment by mnik7044** [comment]
Hey @mrbhatt2348 I created a pull request after adding a favicon to the website please review and merge it.

**Comment by manya0210** [comment]
hello sir... I want to work on this issue under jwoc

**Comment by deepbeatz** [comment]
@mrbhatt2348 I want to work on this issue under JWOC

**Comment by mnik7044** [comment]
I already added the favicon so closing this issue.
