### ISSUE TITLE
Adding Back to Top Button

### ISSUE THREAD

**Issue by Swadhin2001** [mrbhatt2348/iBlog#46]

**Comment by deepbeatz** [comment]
@mrbhatt2348 I want to work on this issue under JWOC

**Comment by SarveshGholap** [comment]
I want to work on this issue under jwoc

**Comment by LuckySingh9897** [comment]
I want to work on this issue under JWOC.

**Comment by manya0210** [comment]
Hello sir ..I want to work on this issue under jwoc

**Comment by SattyamSamania** [comment]
Hey @mrbhatt2348 I want to work on this issue under JWOC. I can create a scroll to Top button using HTML, CSS and Javascript. If you think that would be helpful kindly assign this issue to me. Thank you!

**Comment by Awesomeasma** [comment]
@mrbhatt2348 
I would like to work on this under JWOC. Please assign it to me.

**Comment by KrunalGupta02** [comment]
HI i want to work on this issue under jwoc
