### ISSUE TITLE
Customize the scroll bar 

### ISSUE THREAD

**Issue by zugzwang03** [mrbhatt2348/iBlog#49]
I want to customize the scrollbar, also I want to fix the bug in the navbar, the About and Testimonials link once visited, changes its colour, which looks odd. 
![image](https://user-images.githubusercontent.com/95460021/219557348-7d0b72ac-92a9-4672-b339-c03efd96b2a1.png)
I want to contribute under JWOC'23.

**Comment by ManasaKaza** [comment]
@mrbhatt2348 please add jwoc tag and corresponding difficulty tags
