### ISSUE TITLE
styling the navbar

### ISSUE THREAD

**Issue by vamsikrishnarh7** [mrbhatt2348/iBlog#50]
The expected style will look like the below 

https://user-images.githubusercontent.com/89008784/219560754-f6cbc1a7-ae72-4776-8511-9f8ebfddd0bb.mp4

**Comment by vamsikrishnarh7** [comment]
I want to work on this issue under JWOC. Please assign me this issue

**Comment by mrbhatt2348** [comment]
> The expected style will look like the below 
> 
> https://user-images.githubusercontent.com/89008784/219560754-f6cbc1a7-ae72-4776-8511-9f8ebfddd0bb.mp4
> 
> 

No I do not want this type of design...let it be more attractive...

**Comment by vamsikrishnarh7** [comment]
@mrbhatt2348 can u provide the design. I will code accordingly

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me
