### ISSUE TITLE
Update the featured articles section

### ISSUE THREAD

**Issue by zugzwang03** [mrbhatt2348/iBlog#52]
Can I update the featured articles section with the proper names of blogs and their description in the place of the dummy lorem epsom text? 
![featuredarticles](https://user-images.githubusercontent.com/95460021/219611514-6c252bfb-f8f8-4417-a4b1-812759ab3a6c.png)
I want to make this contribution under JWOC'23.

**Comment by mrbhatt2348** [comment]
@zugzwang03 go on

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by Priyamakeshwari** [comment]
I would like to work on this issue under JWOC
