### ISSUE TITLE
Add some effects on the testimonials cards

### ISSUE THREAD

**Issue by zugzwang03** [mrbhatt2348/iBlog#54]
I want to add some hovering effects on the testimonials cards, like box shadow, z-indexing, scaling, etc.
I want to work on it under JWOC'23.
![image](https://user-images.githubusercontent.com/95460021/219613637-ac9cf7ed-0942-4ff2-b279-e34f6fc05f08.png)

**Comment by mrbhatt2348** [comment]
@zugzwang03  go on, but first complete the task you are assigned right now
