### ISSUE TITLE
Update the UI

### ISSUE THREAD

**Issue by mrbhatt2348** [mrbhatt2348/iBlog#6]
You need to make the website look better by changing its CSS. All the small changes will be welcomed.

**Comment by sagnik3788** [comment]
I would like to work on this issue. Please assign it to me

**Comment by Aniket-011** [comment]
I would like to work on it please assign me.

**Comment by mrbhatt2348** [comment]
@sagnik3788 this issue is classifies as an easy issue, you need to complete it on or before 05:33pm 12-02-2023 to get the required points.

**Comment by mrbhatt2348** [comment]
@Aniket-011  I'm sorry, as the contribution period is not yet started, you are not required to do anything of now, add the pr after contribution period will start

**Comment by sagnik3788** [comment]
okay sir

**Comment by singhalaman23** [comment]
I think according to the rules, assigning of the issues should be done from 15th feb 2023 (12 AM) only. Please verify @mrbhatt2348 @sagnik3788

**Comment by mrbhatt2348** [comment]
> I think according to the rules, assigning of the issues should be done from 15th feb 2023 (12 AM) only. Please verify @mrbhatt2348 @sagnik3788 

Yes I have unassigned him

**Comment by sandeeprawat28** [comment]
Dear mentor, please assign this issue to me.

**Comment by Atul-8115** [comment]
Hello ! mentor pleas assign me this issue

**Comment by Neha00011** [comment]
I want to work on this issue under JWOC.

**Comment by sagnik3788** [comment]
please assign me sir

**Comment by PARASnagpal99** [comment]
I would like to work on this . Please assign this to me .

**Comment by PrachiSingh66** [comment]
Hii, I want to work on this issue under JWOC so please assign it to me.
Thank you

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue, please assign it to me.

**Comment by Aniket-011** [comment]
Please assign me this issue under JWOC

**Comment by Code1705** [comment]
I want o work on this issue  please assign me this under JWOC.
