### ISSUE TITLE
Improvement Of Dark Mode

### ISSUE THREAD

**Issue by psykat1116** [mrbhatt2348/iBlog#64]
The dark mode is not staying consistent as soon as we change the page or refresh the page. I want to work in this issue and improve this .Please Assign me in this project so that i can work under JWoC.

**Comment by mrbhatt2348** [comment]
@psykat1116  go on

**Comment by psykat1116** [comment]
The dark Mode Has Been improved Please Merge it.

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me
