### ISSUE TITLE
Create "Subscribe to our Newsletter" portion

### ISSUE THREAD

**Issue by zugzwang03** [mrbhatt2348/iBlog#67]
As per the objectives of this project, email subscription is an important part of the iBlog website. I wish to create the frontend layout of the same, just above the footer of the home page. 
![image](https://user-images.githubusercontent.com/95460021/219851002-a3ccdb33-db38-45d6-94f2-de34664d4c93.png)
I wish to create this under JWOC'23. @mrbhatt2348 you can

**Comment by neokd** [comment]
I would like to work on this issue under JWOC

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me
