### ISSUE TITLE
Improvement of Navbar in Dark Mode

### ISSUE THREAD

**Issue by ritika728** [mrbhatt2348/iBlog#68]
Hey, I would like to open this issue under JWOC. 
In the dark mode, the navbar links appear to be black. I would like to improve this. 

![photo](https://user-images.githubusercontent.com/91181981/219869221-2abab8a2-73ed-4d38-a151-fd27ff62bd38.png)

**Comment by mrbhatt2348** [comment]
@ritika728 go on

**Comment by ritika728** [comment]
@mrbhatt2348 can you please add the label of category of the issue and the label of JWOC as well

**Comment by mrbhatt2348** [comment]
> @mrbhatt2348 can you please add the label of category of the issue and the label of JWOC as well

Don't worry, that will be added at the time I merge

**Comment by ritika728** [comment]
@mrbhatt2348 can you please add the necessary labels
