### ISSUE TITLE
[DOC] Update Readme file new features

### ISSUE THREAD

**Issue by Suryansh1720001** [mrbhatt2348/iBlog#70]
Hello admin

## Features I want to add - 
- add the contribution guidelines.
- Add the maintainer details
- Add new features for more attractiveness

These are important features of the readme file of any open-source project. kindly assign me this issue.

**Comment by mrbhatt2348** [comment]
@Suryansh1720001 go on

**Comment by Suryansh1720001** [comment]
@mrbhatt2348 
Kindly add the JWOC and the medium/hard label to it. For counting this issue under JWOC

**Comment by Suryansh1720001** [comment]
@mrbhatt2348 
Any update about IWOC labels?

**Comment by mrbhatt2348** [comment]
> @mrbhatt2348 
> Any update about IWOC labels?

I will add after merging, you rather work on the issue

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me
