### ISSUE TITLE
Add the option to rate the blogpost 

### ISSUE THREAD

**Issue by bcsamrudh** [mrbhatt2348/iBlog#71]
Add an option so that the user would be able to rate the blogpost on a scale of 1 to 5.
![image](https://user-images.githubusercontent.com/114090255/219880949-ae10d38d-11cf-4a7d-9467-e9631f197287.png)

I would like to work on this.

**Comment by mrbhatt2348** [comment]
@bcsamrudh go on

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me
