### ISSUE TITLE
Inconsistency of color in dark mode

### ISSUE THREAD

**Issue by ritika728** [mrbhatt2348/iBlog#76]
Hey, I would like to open this issue under JWOC. 
The color of 0/year text should be changed to black and the color of the text in about page should be changed to white. 
![p1](https://user-images.githubusercontent.com/91181981/219948509-90555d4d-f09a-41e6-871d-81b656fe0226.png)
![p2](https://user-images.githubusercontent.com/91181981/219948512-0c854669-e96f-4a6d-bff6-f7cffb8ba80c.png)

**Comment by ritika728** [comment]
@mrbhatt2348 can I work on this issue ?

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me
