### ISSUE TITLE
popup when submitting details in contact section

### ISSUE THREAD

**Issue by ATLAS2002** [mrbhatt2348/iBlog#77]
### showing a thank you message popup, whenever users press submit button, so they know that they have successfully submitted their details.
![iBlog_popup](https://user-images.githubusercontent.com/123821746/220090352-e6c77bb6-9327-4532-a764-aadc25955b7a.png)

**Comment by ATLAS2002** [comment]
can you assign this issue to me under JWOC?

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me
