### ISSUE TITLE
Footer issue

### ISSUE THREAD

**Issue by ritika728** [mrbhatt2348/iBlog#86]
Hey @mrbhatt2348 , I would like to open this issue under JWOC. 
The recent updated footer is not responsive and not similar on all the pages. I would like to add footer on all the pages, improve its look and make it responsive. 
# Home page :
![photo1](https://user-images.githubusercontent.com/91181981/220955987-7b0a477b-5c3c-4fc2-b489-8ef8d19a6675.png)
# All other pages:
![photo](https://user-images.githubusercontent.com/91181981/220956075-e10ef3f8-5f08-4a68-8a59-65034e5dfb2a.png)

**Comment by Hritik1503** [comment]
I am interested to work on this issue under jwoc so i request you to please assign me

**Comment by Priyamakeshwari** [comment]
I would like to work on this issue under JWOC

**Comment by mrbhatt2348** [comment]
> Hey @mrbhatt2348 , I would like to open this issue under JWOC. 
> The recent updated footer is not responsive and not similar on all the pages. I would like to add footer on all the pages, improve its look and make it responsive. 
> # Home page :
> ![photo1](https://user-images.githubusercontent.com/91181981/220955987-7b0a477b-5c3c-4fc2-b489-8ef8d19a6675.png)
> # All other pages:
> ![photo](https://user-images.githubusercontent.com/91181981/220956075-e10ef3f8-5f08-4a68-8a59-65034e5dfb2a.png)
> 

Go on

**Comment by ritika728** [comment]
I am working on this issue. Just getting a little delayed because of my sem exams. Would generate a Pr today itself for sure.

**Comment by ritika728** [comment]
I'll submit a pr for this very soon. Sorry the delay. I have my semester exams going on
