### ISSUE TITLE
Add some more details in sign up page

### ISSUE THREAD

**Issue by zugzwang03** [mrbhatt2348/iBlog#87]
Since it is the sign up page, or to say user registration, shouldn't we add first name, last name, as well as phone number there? 
![image](https://user-images.githubusercontent.com/95460021/220971022-44609742-6450-4d0b-9ef7-5193a69ae786.png)
I want to make this contribution under JWOC. Also let me know any other fields that will suit appropriate while signing up, since if we take all user info while signing up only, it will be easier to relate that with his specific articles, and his other activities.

**Comment by martinCB123456** [comment]
Hi. I want to contribute in this issue can you please assign me

**Comment by Hritik1503** [comment]
I am interested to work on this issue under jwoc so i request you to please assign me

**Comment by mrbhatt2348** [comment]
> Hi. I want to contribute in this issue can you please assign me

Go on

**Comment by zugzwang03** [comment]
> > Hi. I want to contribute in this issue can you please assign me
> 
> Go on

But wasn't the assignment on first come first serve basis?

**Comment by zugzwang03** [comment]
@mrbhatt2348 can I work on it now?
