### ISSUE TITLE
Fix the bug with the images in testimonial section

### ISSUE THREAD

**Issue by zugzwang03** [mrbhatt2348/iBlog#88]
The images in the testimonial section of the customers are not visible. I want to fix this bug under JWOC'23.
![image](https://user-images.githubusercontent.com/95460021/220974026-7d12992c-3f9e-45ac-92b2-3f13c48a75ad.png)

**Comment by Hritik1503** [comment]
I am interested to work on this issue under jwoc so i request you to please assign me

**Comment by mrbhatt2348** [comment]
> The images in the testimonial section of the customers are not visible. I want to fix this bug under JWOC'23.
> ![image](https://user-images.githubusercontent.com/95460021/220974026-7d12992c-3f9e-45ac-92b2-3f13c48a75ad.png)
> 

Go on
