### ISSUE TITLE
Add dark mode button

### ISSUE THREAD

**Issue by mrbhatt2348** [mrbhatt2348/iBlog#9]

**Comment by Laxmankohar** [comment]
Hey @mrbhatt2348 I would like to work on this issue. Can you please assign it to me?

**Comment by mrbhatt2348** [comment]
> Hey @mrbhatt2348 I would like to work on this issue. Can you please assign it to me?
> 

Okay you can contribute to it, just add the changes and pull the merge request

**Comment by Aniket-011** [comment]
Hi I would like to contribute in it please assign it to me.

**Comment by mrbhatt2348** [comment]
@Laxmankohar @Aniket-011 I have assigned this issue to you both, according to the guidlines given to me, i am considering it an medium issue, so it must be completed in the next two days i.e. on or before 5:30 p.m. on 13-02-23. Please keep this into consideration.

**Comment by mrbhatt2348** [comment]
@Laxmankohar @Aniket-011  I'm sorry, as the contribution period is not yet started, you are not required to do anything of now, add the pr after contribution period will start

**Comment by KrunalGupta02** [comment]
@mrbhatt2348 can i work on it i want to contribute in this project

**Comment by yeager404** [comment]
Would like to work on this issue.

**Comment by anvi2901** [comment]
Kindly assign this issue to me

**Comment by RishabhJain0721** [comment]
I want to work under this issue under JWOC.

**Comment by RishabhJain0721** [comment]
I want to work under this issue under JWOC.

**Comment by Laxmankohar** [comment]
Hey @mrbhatt2348 I would like to work on this issue. Can you please assign it to me?

**Comment by yeager404** [comment]
I would like to work on this issue. Kindly consider assigning this to me. Under JWOC .

**Comment by taniaban2712** [comment]
I want to work on this issue under JWOC.

**Comment by Viveksati5143** [comment]
please assign me this issue

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC

**Comment by KrunalGupta02** [comment]
I want to work on this issue under JWOC

**Comment by vermaanurag1532** [comment]
I want to contribute on this issue under JWOC

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue, please assign it to me under JWOC.

**Comment by SubhajitB05** [comment]
"I want to work on this issue under JWOC"

**Comment by bhavya321321** [comment]
I want to work under this issue on JWOC assign me

**Comment by Pritam991** [comment]
i am working on this .

**Comment by RishabhJain0721** [comment]
Hi @mrbhatt2348 
I have raised a PR.Could you please review it?

**Comment by RishabhJain0721** [comment]
Hi @mrbhatt2348
I have done the required changes in the button and raised a PR.Could you please review it?
