### ISSUE TITLE
Update contact page

### ISSUE THREAD

**Issue by khushimarothi** [mrbhatt2348/iBlog#90]
Want to update the contact page UI and validate the form.
please assign under JWOC

**Comment by Hritik1503** [comment]
I am interested to work on this issue under jwoc so i request you to please assign me

**Comment by Priyamakeshwari** [comment]
I would like to work on this issue under JWOC

**Comment by mrbhatt2348** [comment]
> I am interested to work on this issue under jwoc so i request you to please assign me

Go on

**Comment by khushimarothi** [comment]
I created the issue and it should be assigned to me. Can I know why you assigned it to someone else?
@mrbhatt2348

**Comment by mrbhatt2348** [comment]
> I created the issue and it should be assigned to me. Can I know why you assigned it to someone else?
> @mrbhatt2348 

I have assigned you one issue already, according to rules I cannot assign you another one.

**Comment by khushimarothi** [comment]
That's an easy one . As much as I know one person can work on 2issues at a time.

**Comment by khushimarothi** [comment]
Are you going to assign same labels for both issues?

**Comment by khushimarothi** [comment]
@mrbhatt2348 check i did that now please assign it too me

**Comment by khushimarothi** [comment]
I am interested to work back on this issue. 
@mrbhatt2348

**Comment by khushimarothi** [comment]
assign it to me :) @mrbhatt2348
