### ISSUE TITLE
Make the title clickable

### ISSUE THREAD

**Issue by S-ishita** [mrbhatt2348/iBlog#92]
When you click on the title of the website, it redirects to the homepage. So whichever segment you are in of the website, you can easily return to home page with one click.

**Comment by S-ishita** [comment]
Please assign this issue to me under JWOC.

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by mrbhatt2348** [comment]
> Please assign this issue to me under JWOC.
> 

Go on
